services:
  database:
    image: postgres:17.2
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./config:/docker-entrypoint-initdb.d

  client-dev:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    platform: linux/amd64
    environment:
      MS_TRANSACTION_HOST: ${MS_TRANSACTION_HOST}
      MS_USER_HOST: ${MS_USER_HOST}
      MS_VEHICLE_HOST: ${MS_VEHICLE_HOST}
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules

  client-prod:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: prod
    platform: linux/amd64
    environment:
      MS_TRANSACTION_HOST: ${MS_TRANSACTION_HOST}
      MS_USER_HOST: ${MS_USER_HOST}
      MS_VEHICLE_HOST: ${MS_VEHICLE_HOST}
      NODE_ENV: production
    ports:
      - "80:80"
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules

  ms-transaction:
    build:
      context: ./microservices/transaction
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DB_NAME: ${POSTGRES_DB_NAME}
      DB_USER: ${POSTGRES_DB_USER}
      DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      DB_HOST: ${POSTGRES_DB_HOST}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      CLIENT_HOST: ${CLIENT_HOST}
    ports:
      - "3001:3001"
    volumes:
      - ./microservices/transaction:/app
      - ./microservices/shared:/app/shared

  ms-user:
    build:
      context: ./microservices/user
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DB_NAME: ${POSTGRES_DB_NAME}
      DB_USER: ${POSTGRES_DB_USER}
      DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      DB_HOST: ${POSTGRES_DB_HOST}
      DB_PORT: ${POSTGRES_DB_PORT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      CLIENT_HOST: ${CLIENT_HOST}
    ports:
      - "3002:3002"
    volumes:
      - ./microservices/user:/app
      - ./microservices/shared:/app/shared

  ms-vehicle:
    build:
      context: ./microservices/vehicle
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DB_NAME: ${POSTGRES_DB_NAME}
      DB_USER: ${POSTGRES_DB_USER}
      DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      DB_HOST: ${POSTGRES_DB_HOST}
      DB_PORT: ${POSTGRES_DB_PORT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      CLIENT_HOST: ${CLIENT_HOST}
    ports:
      - "3003:3003"
    volumes:
      - ./microservices/vehicle:/app
      - ./microservices/shared:/app/shared

volumes:
  node_modules:
