services:
  database:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mmotor
    ports:
      - 5432:5432
    volumes:
      - ./config:/docker-entrypoint-initdb.d
      # - ./db-data/:/var/lib/postgresql/data/

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "4200:4200"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  file:
    build:
      context: ./microservices/file
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./microservices/file:/usr/src/app
      - ./microservices/shared:/app/shared
    depends_on:
      - database

  user:
    build:
      context: ./microservices/user
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./microservices/user:/usr/src/app
      - ./microservices/shared:/app/shared
    depends_on:
      - database

  vehicle:
    build:
      context: ./microservices/vehicle
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./microservices/vehicle:/usr/src/app
      - ./microservices/shared:/app/shared
    depends_on:
      - database
