export enum VehicleType {
  Sale = "Vente",
  Rental = "Location",
}

export enum VehicleBrand {
  Renault = "Renault",
  Peugeot = "Peugeot",
  Dacia = "Dacia",
  Citroen = "Citroën",
  Volkswagen = "Volkswagen",
  Toyota = "Toyota",
  Tesla = "Tesla",
  BMW = "BMW",
  Mercedes = "Mercedes",
  Ford = "Ford",
  Audi = "Audi",
  Hyundai = "Hyundai",
  Kia = "Kia",
  Opel = "Opel",
  Fiat = "Fiat",
  Skoda = "Škoda",
  Nissan = "Nissan",
  MG = "MG",
  Mini = "Mini",
  DS = "DS",
  Suzuki = "Suzuki",
  Seat = "Seat",
  Volvo = "Volvo",
  Cupra = "Cupra",
  Jeep = "Jeep",
  LandRover = "Land Rover",
  Lexus = "Lexus",
  AlfaRomeo = "Alfa Romeo",
  Porsche = "Porsche",
  LynkCo = "Lynk & Co",
  Alpine = "Alpine",
  Mitsubishi = "Mitsubishi",
  Smart = "Smart",
  Jaguar = "Jaguar",
  Abarth = "Abarth",
  Maserati = "Maserati",
  Lotus = "Lotus",
  Lamborghini = "Lamborghini",
  Bentley = "Bentley",
  RollsRoyce = "Rolls Royce",
  Mobilize = "Mobilize",
  Bugatti = "Bugatti",
}

export enum VehicleEnergy {
  Electric = "Electrique",
  Diesel = "Diesel",
  Hybrid = "Hybride",
  Gasoline = "Essence",
}

export enum VehicleCategory {
  SUV = "SUV",
  Sedan = "Berline",
  Compact = "Compacte",
  CityCar = "Citadine",
  Convertible = "Cabriolet",
  Coupe = "Coupé",
  StationWagon = "Break",
  Minivan = "Monospace",
  Pickup = "Pick-up",
  Roadster = "Roadster",
  OffRoad = "Tout-terrain",
  Supercar = "Supercar",
  Hypercar = "Hypercar",
  TwoWheels = "2 Roues",
}
