import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class DashboardService {
  constructor() {}

  getvehicleData() {
    return [
      {
        id: 1,
        model: "Clio",
        year: 2020,
        km: 15_000,
        price: 12_000,
        type: "Vente",
        brand: "Renault",
        energy: "Essence",
        category: "Citadine",
        description: "Petite voiture économique et fiable.",
      },
      {
        id: 2,
        model: "208",
        year: 2022,
        km: 5_000,
        price: 18_000,
        type: "Vente",
        brand: "Peugeot",
        energy: "Electrique",
        category: "Compacte",
        description: "Compacte moderne et écologique.",
      },
      {
        id: 3,
        model: "Model 3",
        year: 2023,
        km: 10_000,
        price: 500,
        type: "Location",
        brand: "Tesla",
        energy: "Electrique",
        category: "Berline",
        description: "Véhicule électrique haut de gamme.",
      },
      {
        id: 4,
        model: "Golf",
        year: 2021,
        km: 12_000,
        price: 22_000,
        type: "Vente",
        brand: "Volkswagen",
        energy: "Diesel",
        category: "Compacte",
        description: "Compacte pratique avec bon rendement.",
      },
      {
        id: 5,
        model: "Tiguan",
        year: 2022,
        km: 8_000,
        price: 700,
        type: "Location",
        brand: "Volkswagen",
        energy: "Hybride",
        category: "SUV",
        description: "SUV hybride tout terrain.",
      },
      {
        id: 6,
        model: "Mustang",
        year: 2020,
        km: 18_000,
        price: 35_000,
        type: "Vente",
        brand: "Ford",
        energy: "Essence",
        category: "Coupé",
        description: "Voiture sport iconique.",
      },
      {
        id: 7,
        model: "Model X",
        year: 2021,
        km: 5_000,
        price: 800,
        type: "Location",
        brand: "Tesla",
        energy: "Electrique",
        category: "SUV",
        description: "SUV électrique de luxe.",
      },
      {
        id: 8,
        model: "Peugeot 3008",
        year: 2020,
        km: 25_000,
        price: 28_000,
        type: "Vente",
        brand: "Peugeot",
        energy: "Diesel",
        category: "SUV",
        description: "SUV familial pratique et spacieux.",
      },
      {
        id: 9,
        model: "Mini Cooper",
        year: 2021,
        km: 15_000,
        price: 400,
        type: "Location",
        brand: "Mini",
        energy: "Essence",
        category: "Cabriolet",
        description: "Cabriolet fun et dynamique.",
      },
      {
        id: 10,
        model: "F-Type",
        year: 2022,
        km: 3_000,
        price: 60_000,
        type: "Vente",
        brand: "Jaguar",
        energy: "Essence",
        category: "Coupé",
        description: "Voiture de sport haut de gamme.",
      },
    ];
  }
}
