name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create .env file
        run: |
          touch .env
          echo "POSTGRES_DB_NAME=${{ secrets.POSTGRES_DB_NAME }}" >> .env
          echo "POSTGRES_DB_USER=${{ secrets.POSTGRES_DB_USER }}" >> .env
          echo "POSTGRES_DB_PASSWORD=${{ secrets.POSTGRES_DB_PASSWORD }}" >> .env
          echo "POSTGRES_DB_HOST=${{ secrets.POSTGRES_DB_HOST }}" >> .env
          echo "POSTGRES_DB_PORT=${{ secrets.POSTGRES_DB_PORT }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "CLIENT_HOST=${{ secrets.CLIENT_HOST }}" >> .env
          echo "MS_TRANSACTION_HOST=${{ secrets.MS_TRANSACTION_HOST }}" >> .env
          echo "MS_USER_HOST=${{ secrets.MS_USER_HOST }}" >> .env
          echo "MS_VEHICLE_HOST=${{ secrets.MS_VEHICLE_HOST }}" >> .env
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> .env

      - name: Deploy to EC2 Frontend
        run: |
          scp -o StrictHostKeyChecking=no -r client ec2-user@${{ secrets.EC2_FRONTEND_IP }}:/home/ec2-user
          scp -o StrictHostKeyChecking=no compose.yaml ec2-user@${{ secrets.EC2_FRONTEND_IP }}:/home/ec2-user
          scp -o StrictHostKeyChecking=no .env ec2-user@${{ secrets.EC2_FRONTEND_IP }}:/home/ec2-user
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_FRONTEND_IP }} << 'EOF'
            docker-compose down
            docker-compose up -d client
          EOF

      # - name: Deploy to EC2 Transaction
      #   run: |
      #     scp -o StrictHostKeyChecking=no -r microservices/shared ec2-user@${{ secrets.EC2_TRANSACTION_IP }}:/home/ec2-user
      #     scp -o StrictHostKeyChecking=no -r microservices/transaction ec2-user@${{ secrets.EC2_TRANSACTION_IP }}:/home/ec2-user
      #     scp -o StrictHostKeyChecking=no compose.yaml ec2-user@${{ secrets.EC2_TRANSACTION_IP }}:/home/ec2-user
      #     scp -o StrictHostKeyChecking=no .env ec2-user@${{ secrets.EC2_TRANSACTION_IP }}:/home/ec2-user
      #     ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_TRANSACTION_IP }} << 'EOF'
      #       docker-compose down
      #       docker-compose up -d ms-transaction
      #     EOF

      # - name: Deploy to EC2 User
      #   run: |
      #     scp -o StrictHostKeyChecking=no -r microservices/shared ec2-user@${{ secrets.EC2_USER_IP }}:/home/ec2-user
      #     scp -o StrictHostKeyChecking=no -r microservices/user ec2-user@${{ secrets.EC2_USER_IP }}:/home/ec2-user
      #     scp -o StrictHostKeyChecking=no compose.yaml ec2-user@${{ secrets.EC2_USER_IP }}:/home/ec2-user
      #     scp -o StrictHostKeyChecking=no .env ec2-user@${{ secrets.EC2_USER_IP }}:/home/ec2-user
      #     ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_USER_IP }} << 'EOF'
      #       docker-compose down
      #       docker-compose up -d ms-user
      #     EOF

      # - name: Deploy to EC2 Vehicle
      #   run: |
      #     scp -o StrictHostKeyChecking=no -r microservices/shared ec2-user@${{ secrets.EC2_VEHICLE_IP }}:/home/ec2-user
      #     scp -o StrictHostKeyChecking=no -r microservices/vehicle ec2-user@${{ secrets.EC2_VEHICLE_IP }}:/home/ec2-user
      #     scp -o StrictHostKeyChecking=no compose.yaml ec2-user@${{ secrets.EC2_VEHICLE_IP }}:/home/ec2-user
      #     scp -o StrictHostKeyChecking=no .env ec2-user@${{ secrets.EC2_VEHICLE_IP }}:/home/ec2-user
      #     ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_VEHICLE_IP }} << 'EOF'
      #       docker-compose down
      #       docker-compose up -d ms-vehicle
      #     EOF
