name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - 44-cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.LIGHTSAIL_IP }} >> ~/.ssh/known_hosts

    - name: Deploy with Docker Compose
      run: |
        ssh -T ubuntu@${{ secrets.LIGHTSAIL_IP }} << 'EOF'
          cd MoMotors
          sudo git pull origin main

          sudo touch .env
          sudo chmod +w .env
          sudo echo "POSTGRES_DB_NAME=${{ secrets.POSTGRES_DB_NAME }}" > .env
          sudo echo "POSTGRES_DB_USER=${{ secrets.POSTGRES_DB_USER }}" >> .env
          sudo echo "POSTGRES_DB_PASSWORD=${{ secrets.POSTGRES_DB_PASSWORD }}" >> .env
          sudo echo "POSTGRES_DB_HOST=${{ secrets.POSTGRES_DB_HOST }}" >> .env
          sudo echo "POSTGRES_DB_PORT=${{ secrets.POSTGRES_DB_PORT }}" >> .env
          
          docker-compose down
          docker-compose build
        EOF
